PROJECTNAME=sdlbootstrap
CC=g++
SOURCEDIR=src/
OUTPUTDIR=build/
INCLUDE_PATHS=-Isdl/include/SDL2
LIBRARY_PATHS=-Lsdl/lib
COMPILER_FLAGS=-Wall
LINKER_FLAGS=-lSDL2 -lSDL2Main

all:
	$(CC) $(SOURCEDIR)main.cpp $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OUTPUTDIR)$(PROJECTNAME)
